### ISSUE TITLE
Deprecated notices in nette 2.4

### ISSUE THREAD

**Issue by Budik** [iPublikuj/oauth#1]
After updating to nette 2.4 (which implemented a lot of deprecated notices) ipub/twitter started throwing these:

exception 'ErrorException' with message 'Nette\Utils\Html::add() is deprecated, use addHtml() or addText() instead.' in ...\vendor\nette\utils\src\Utils\Html.php:370
Stack trace:
#0 [internal function]: Tracy\Bar->Tracy\{closure}(16384, 'Nette\\Utils\\Htm...', 'D:\\Web\\zeedee\\v...', 370, Array)
#1 ...\vendor\nette\utils\src\Utils\Html.php(370): trigger_error('Nette\\Utils\\Htm...', 16384)
#2 ...\vendor\ipub\oauth\src\IPub\OAuth\Diagnostics\Panel.php(74): Nette\Utils\Html->add(Object(Nette\Utils\Html))
#3 ...\vendor\tracy\tracy\src\Tracy\Bar.php(131): IPub\OAuth\Diagnostics\Panel->getTab()
#4 ...\vendor\tracy\tracy\src\Tracy\Bar.php(89): Tracy\Bar->renderPanels()
#5 ...\vendor\tracy\tracy\src\Tracy\Debugger.php(254): Tracy\Bar->render()
#6 [internal function]: Tracy\Debugger::shutdownHandler()
#7 {main}

**Comment by akadlec** [comment]
Yes this is known issue.
